# Generated by Django 4.0.5 on 2022-06-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=models.TextField(verbose_name=" What's on your mind ?"),
        ),
    ]
